<a href="https://colab.research.google.com/github/wichung/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_5%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 5강 - 데이터 저장

## 5-1 CSV 형식 저장

In [2]:
import pandas as pd

data = {
    'student_id': [101, 102, 103, 104, 105],
    'database_score': [85, 76, 92, 63, 88],
    'cloudcomputing_score': [78, 82, 95, 70, 84],
    'python_score': [92, 78, 85, 75, 91],
    'watch_rate': [0.95, 0.87, 0.99, 0.80, 0.93]
}
## DataFrame 생성
df = pd.DataFrame(data)

## CSV 형식 저장
df.to_csv('student_analysis.csv', encoding = 'utf-8', index=False)

## 5-2 JSON 형식 저장

In [4]:
### 라이브러리 임포트
import json
import pandas as pd

data = {
    "이름": "홍길동",
    "나이": 25,
    "거주지": "서울",
    "관심사": ["프로그래밍", "데이터 분석", "여행"]
}

## json.dump를 이용한 저장
with open('output', mode='w', encoding='utf-8') as f:
    json.dump(data, f, indent =4, ensure_ascii=False)

## DataFrame을 이용한 저장
df=pd.DataFrame(data)
df.to_json('output_df.json', orient='records', indent=4, force_ascii=False)

In [6]:
# colmun 단위
## DataFrame을 이용한 저장
df=pd.DataFrame([data])
df.to_json('output_df.json', orient='columns', indent=4, force_ascii=False)

## 5-3 Pandas Dataframe 데이터 추출

In [8]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터학", "경영학", "농학", "교육학", "영어영문학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)
df

    이름  학년   학점     학과    동아리
0  김철수   1  4.2   컴퓨터학  프로그래밍
1  이영희   2  3.8    경영학   독서토론
2  박민수   3  4.5     농학   로봇공학
3  최지훈   4  3.9    교육학   봉사활동
4  정소희   2  3.5  영어영문학   음악감상

In [11]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터학", "경영학", "농학", "교육학", "영어영문학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)
df

## DataFrame 인덱스 출력
#print("index:\n", df.index)
print(df.index)

## DataFrame 컬럼 출력
#print("\ncolumns:\n", df.columns)
print(df.columns)
## DataFrame 행 출력
#print("\nvalus:\n", df.values)
print(df.values.tolist())
print(df.values)

## DataFrame 값 출력
#print("\nrows:\n", df.values.tolist())
print(df.values.flatten())

RangeIndex(start=0, stop=5, step=1)
Index(['이름', '학년', '학점', '학과', '동아리'], dtype='object')
[['김철수', 1, 4.2, '컴퓨터학', '프로그래밍'], ['이영희', 2, 3.8, '경영학', '독서토론'], ['박민수', 3, 4.5, '농학', '로봇공학'], ['최지훈', 4, 3.9, '교육학', '봉사활동'], ['정소희', 2, 3.5, '영어영문학', '음악감상']]
[['김철수' 1 4.2 '컴퓨터학' '프로그래밍']
 ['이영희' 2 3.8 '경영학' '독서토론']
 ['박민수' 3 4.5 '농학' '로봇공학']
 ['최지훈' 4 3.9 '교육학' '봉사활동']
 ['정소희' 2 3.5 '영어영문학' '음악감상']]
['김철수' 1 4.2 '컴퓨터학' '프로그래밍' '이영희' 2 3.8 '경영학' '독서토론' '박민수' 3 4.5 '농학'
 '로봇공학' '최지훈' 4 3.9 '교육학' '봉사활동' '정소희' 2 3.5 '영어영문학' '음악감상']

## 5-4 DataFrame 생성 방법

In [13]:
import pandas as pd
import json

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## 딕셔너리, csv, json으로 부터 DataFrame 생성
df1 = pd.DataFrame.from_dict(data)
df2 = pd.read_csv('students.csv')
df3 = pd.read_json('students.json')

## 세가지 방법 결과 비교
print(df1.shape)
print(df2.shape)
print(df3.shape)

(5, 5)
(5, 5)
(5, 5)

## 5-5 DataFrame 저장 방법

In [16]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## Dataframe 생성
df1 = pd.DataFrame(data)

## CSV, JSON 형식으로 저장
df.to_csv('students_sores.csv')
df.to_json('students_sores.json')


## HTML 형식으로 저장
html_table = df.to_html()
with open('students_scores.html', 'w') as f:
    f.write(html_table)

## 5-6 실습 시나리오

## 데이터 수집

In [ ]:
import requests

url = "http://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getMinuDustFrcstDspth"
api_key = '[발급받은 인증키]'

params = {
    'serviceKey': api_key,
    'returnType': 'json',
    'numOfRows': '100',
    'pageNo': '1',
    'sidoName': '서울',
    'ver': '1.0'
}

## 데이터 수집
response = requests.get(url, params=params)

## 호출 성공/실패 출력

In [17]:
# 서울시 자료
import requests

url = "http://openapi.seoul.go.kr:8088/52/json/energyUseDataStatInfo/1/5/2015/01"
api_key = '152'

params = {
    'serviceKey': api_key,
    'returnType': 'json',
    'numOfRows': '100',
    'pageNo': '1',
    'sidoName': '서울',
    'ver': '1.0'
}

## 데이터 수집
response = requests.get(url, params=params)

## 호출 성공/실패 출력
print(response.json())

{'energyUseDataStatInfo': {'list_total_count': 2955, 'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'}, 'row': [{'YEAR': '2015', 'MON': '01', 'HOSTCODE': '광진구', 'DONGCODE': '기타', 'MM_TYPE': '기업', 'TYPE_DIV': '단체', 'TYPE_DIV_CD': 'TB_GROUP', 'CNT': '1', 'EUS': '361', 'EUS1': '322', 'EUS2': '347', 'ECO2_1_MATH_YEAR': '39', 'ECO2_2_MATH_YEAR': '16.536', 'ECO2_1_MATH': '26.5', 'ECO2_2_MATH': '11.236', 'ECO2_1': '26.5', 'ECO2_2': '11.236', 'E_TOE_YEAR': '0.00897', 'E_RATE_YEAR': '12.112', 'E_TOE_AVG': '0.006', 'E_RATE_AVG': '7.922', 'GUS': '0', 'GUS1': '0', 'GUS2': '0', 'GCO2_1_MATH_YEAR': '0', 'GCO2_2_MATH_YEAR': '0', 'GCO2_1_MATH': '0', 'GCO2_2_MATH': '0', 'GCO2_1': '0', 'GCO2_2': '0', 'G_TOE_YEAR': '0', 'G_RATE_YEAR': '0', 'G_TOE_AVG': '0', 'G_RATE_AVG': '0', 'WUS': '0', 'WUS1': '0', 'WUS2': '0', 'WCO2_1_MATH_YEAR': '0', 'WCO2_2_MATH_YEAR': '0', 'WCO2_1_MATH': '0', 'WCO2_2_MATH': '0', 'WCO2_1': '0', 'WCO2_2': '0', 'W_RATE_YEAR': '0', 'W_RATE_AVG': '0', 'HUS': '0', 'HUS1': '0', 'HUS2': '0', 'HCO2_1': '0', 'HCO2_2': '0', 'H_RATE_YEAR': '0', 'H_RATE_AVG': '0', 'NOW_CO2': '153.064', 'YEAR_CO2': '136.528', 'AVG_CO2': '141.828', 'TOTAL_CO2_YEAR': '16.536', 'TOTAL_CO2_AVG': '11.236', 'TOTAL_RATE_YEAR': '12.112', 'TOTAL_RATE_AVG': '7.922', 'REG_DATE': '2015-06-04 17:03:55.0'}, {'YEAR': '2015', 'MON': '01', 'HOSTCODE': '중구', 'DONGCODE': '황학동', 'MM_TYPE': '소상공인', 'TYPE_DIV': '단체', 'TYPE_DIV_CD': 'TB_GROUP', 'CNT': '1', 'EUS': '1405', 'EUS1': '1400', 'EUS2': '1538', 'ECO2_1_MATH_YEAR': '5', 'ECO2_2_MATH_YEAR': '2.12', 'ECO2_1_MATH': '-64', 'ECO2_2_MATH': '-27.136', 'ECO2_1': '-64', 'ECO2_2': '-27.136', 'E_TOE_YEAR': '0.00115', 'E_RATE_YEAR': '0.357', 'E_TOE_AVG': '-0.015', 'E_RATE_AVG': '-4.357', 'GUS': '0', 'GUS1': '0', 'GUS2': '0', 'GCO2_1_MATH_YEAR': '0', 'GCO2_2_MATH_YEAR': '0', 'GCO2_1_MATH': '0', 'GCO2_2_MATH': '0', 'GCO2_1': '0', 'GCO2_2': '0', 'G_TOE_YEAR': '0', 'G_RATE_YEAR': '0', 'G_TOE_AVG': '0', 'G_RATE_AVG': '0', 'WUS': '0', 'WUS1': '0', 'WUS2': '0', 'WCO2_1_MATH_YEAR': '0', 'WCO2_2_MATH_YEAR': '0', 'WCO2_1_MATH': '0', 'WCO2_2_MATH': '0', 'WCO2_1': '0', 'WCO2_2': '0', 'W_RATE_YEAR': '0', 'W_RATE_AVG': '0', 'HUS': '0', 'HUS1': '0', 'HUS2': '0', 'HCO2_1': '0', 'HCO2_2': '0', 'H_RATE_YEAR': '0', 'H_RATE_AVG': '0', 'NOW_CO2': '595.72', 'YEAR_CO2': '593.6', 'AVG_CO2': '622.856', 'TOTAL_CO2_YEAR': '2.12', 'TOTAL_CO2_AVG': '-27.136', 'TOTAL_RATE_YEAR': '0.357', 'TOTAL_RATE_AVG': '-4.357', 'REG_DATE': '2015-06-04 17:03:55.0'}, {'YEAR': '2015', 'MON': '01', 'HOSTCODE': '중랑구', 'DONGCODE': '면목3.8동', 'MM_TYPE': '개인', 'TYPE_DIV': '아파트', 'TYPE_DIV_CD': 'TB_APT_C', 'CNT': '1', 'EUS': '215', 'EUS1': '250', 'EUS2': '250', 'ECO2_1_MATH_YEAR': '-35', 'ECO2_2_MATH_YEAR': '-14.84', 'ECO2_1_MATH': '-35', 'ECO2_2_MATH': '-14.84', 'ECO2_1': '-35', 'ECO2_2': '-14.84', 'E_TOE_YEAR': '-0.00805', 'E_RATE_YEAR': '-14', 'E_TOE_AVG': '-0.008', 'E_RATE_AVG': '-14', 'GUS': '0', 'GUS1': '0', 'GUS2': '0', 'GCO2_1_MATH_YEAR': '0', 'GCO2_2_MATH_YEAR': '0', 'GCO2_1_MATH': '0', 'GCO2_2_MATH': '0', 'GCO2_1': '0', 'GCO2_2': '0', 'G_TOE_YEAR': '0', 'G_RATE_YEAR': '0', 'G_TOE_AVG': '0', 'G_RATE_AVG': '0', 'WUS': '0', 'WUS1': '0', 'WUS2': '0', 'WCO2_1_MATH_YEAR': '0', 'WCO2_2_MATH_YEAR': '0', 'WCO2_1_MATH': '0', 'WCO2_2_MATH': '0', 'WCO2_1': '0', 'WCO2_2': '0', 'W_RATE_YEAR': '0', 'W_RATE_AVG': '0', 'HUS': '0', 'HUS1': '0', 'HUS2': '0', 'HCO2_1': '0', 'HCO2_2': '0', 'H_RATE_YEAR': '0', 'H_RATE_AVG': '0', 'NOW_CO2': '91.16', 'YEAR_CO2': '106', 'AVG_CO2': '106', 'TOTAL_CO2_YEAR': '-14.84', 'TOTAL_CO2_AVG': '-14.84', 'TOTAL_RATE_YEAR': '-14', 'TOTAL_RATE_AVG': '-14', 'REG_DATE': '2015-06-04 17:03:55.0'}, {'YEAR': '2015', 'MON': '01', 'HOSTCODE': '강동구', 'DONGCODE': '강일동', 'MM_TYPE': '공동주택관리소', 'TYPE_DIV': '단체', 'TYPE_DIV_CD': 'TB_GROUP', 'CNT': '10', 'EUS': '1176691', 'EUS1': '1189993', 'EUS2': '1283702', 'ECO2_1_MATH_YEAR': '-13302', 'ECO2_2_MATH_YEAR': '-5640.048', 'ECO2_1_MATH': '-60156.5', 'ECO2_2_MATH': '-25506.356', 'ECO2_1': '-60156.5', 'ECO2_2': '-25506.356', 'E_TOE_YEAR': '-3.05946', 'E_RATE_YEAR': '-1.118', 'E_TOE_AVG': '-13.836', 'E_RATE_AVG': '-4.864', 'GUS': '36', 'GUS1': '34', 'GUS2': '35', 'GCO2_1_MATH_YEAR': '2', 'GCO2_2_MATH_YEAR': '4.48', 'GCO2_1_MATH': '1.5', 'GCO2_2_MATH': '3.36', 'GCO2_1': '1.5', 'GCO2_2': '3.36', 'G_TOE_YEAR': '0.002', 'G_RATE_YEAR': '5.882', 'G_TOE_AVG': '0.002', 'G_RATE_AVG': '4.348', 'WUS': '36421', 'WUS1': '34701', 'WUS2': '35251', 'WCO2_1_MATH_YEAR': '1720', 'WCO2_2_MATH_YEAR': '571.04', 'WCO2_1_MATH': '1445', 'WCO2_2_MATH': '479.74', 'WCO2_1': '1445', 'WCO2_2': '479.74', 'W_RATE_YEAR': '4.957', 'W_RATE_AVG': '4.131', 'HUS': '0', 'HUS1': '0', 'HUS2': '0', 'HCO2_1': '0', 'HCO2_2': '0', 'H_RATE_YEAR': '0', 'H_RATE_AVG': '0', 'NOW_CO2': '511089.396', 'YEAR_CO2': '516153.924', 'AVG_CO2': '536112.652', 'TOTAL_CO2_YEAR': '-5064.528', 'TOTAL_CO2_AVG': '-25023.256', 'TOTAL_RATE_YEAR': '-0.981', 'TOTAL_RATE_AVG': '-4.668', 'REG_DATE': '2015-06-04 17:03:55.0'}, {'YEAR': '2015', 'MON': '01', 'HOSTCODE': '강동구', 'DONGCODE': '강일동', 'MM_TYPE': '기업', 'TYPE_DIV': '단체', 'TYPE_DIV_CD': 'TB_GROUP', 'CNT': '6', 'EUS': '3192', 'EUS1': '2187', 'EUS2': '2187', 'ECO2_1_MATH_YEAR': '1005', 'ECO2_2_MATH_YEAR': '426.12', 'ECO2_1_MATH': '1005', 'ECO2_2_MATH': '426.12', 'ECO2_1': '1005', 'ECO2_2': '426.12', 'E_TOE_YEAR': '0.23115', 'E_RATE_YEAR': '45.953', 'E_TOE_AVG': '0.231', 'E_RATE_AVG': '45.953', 'GUS': '84', 'GUS1': '76', 'GUS2': '67', 'GCO2_1_MATH_YEAR': '8', 'GCO2_2_MATH_YEAR': '17.92', 'GCO2_1_MATH': '12.5', 'GCO2_2_MATH': '28', 'GCO2_1': '12.5', 'GCO2_2': '28', 'G_TOE_YEAR': '0.008', 'G_RATE_YEAR': '10.526', 'G_TOE_AVG': '0.013', 'G_RATE_AVG': '17.483', 'WUS': '0', 'WUS1': '0', 'WUS2': '0', 'WCO2_1_MATH_YEAR': '0', 'WCO2_2_MATH_YEAR': '0', 'WCO2_1_MATH': '0', 'WCO2_2_MATH': '0', 'WCO2_1': '0', 'WCO2_2': '0', 'W_RATE_YEAR': '0', 'W_RATE_AVG': '0', 'HUS': '0', 'HUS1': '0', 'HUS2': '0', 'HCO2_1': '0', 'HCO2_2': '0', 'H_RATE_YEAR': '0', 'H_RATE_AVG': '0', 'NOW_CO2': '1541.568', 'YEAR_CO2': '1097.528', 'AVG_CO2': '1087.448', 'TOTAL_CO2_YEAR': '444.04', 'TOTAL_CO2_AVG': '454.12', 'TOTAL_RATE_YEAR': '40.458', 'TOTAL_RATE_AVG': '41.76', 'REG_DATE': '2015-06-04 17:03:55.0'}]}}

In [18]:
response.json()

{'energyUseDataStatInfo': {'list_total_count': 2955,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'YEAR': '2015',
    'MON': '01',
    'HOSTCODE': '광진구',
    'DONGCODE': '기타',
    'MM_TYPE': '기업',
    'TYPE_DIV': '단체',
    'TYPE_DIV_CD': 'TB_GROUP',
    'CNT': '1',
    'EUS': '361',
    'EUS1': '322',
    'EUS2': '347',
    'ECO2_1_MATH_YEAR': '39',
    'ECO2_2_MATH_YEAR': '16.536',
    'ECO2_1_MATH': '26.5',
    'ECO2_2_MATH': '11.236',
    'ECO2_1': '26.5',
    'ECO2_2': '11.236',
    'E_TOE_YEAR': '0.00897',
    'E_RATE_YEAR': '12.112',
    'E_TOE_AVG': '0.006',
    'E_RATE_AVG': '7.922',
    'GUS': '0',
    'GUS1': '0',
    'GUS2': '0',
    'GCO2_1_MATH_YEAR': '0',
    'GCO2_2_MATH_YEAR': '0',
    'GCO2_1_MATH': '0',
    'GCO2_2_MATH': '0',
    'GCO2_1': '0',
    'GCO2_2': '0',
    'G_TOE_YEAR': '0',
    'G_RATE_YEAR': '0',
    'G_TOE_AVG': '0',
    'G_RATE_AVG': '0',
    'WUS': '0',
    'WUS1': '0',
    'WUS2': '0',
    'WCO2_1_MATH_YEAR': '0',
    'WCO2_2_MATH_YEAR': '0',
    'WCO2_1_MATH': '0',
    'WCO2_2_MATH': '0',
    'WCO2_1': '0',
    'WCO2_2': '0',
    'W_RATE_YEAR': '0',
    'W_RATE_AVG': '0',
    'HUS': '0',
    'HUS1': '0',
    'HUS2': '0',
    'HCO2_1': '0',
    'HCO2_2': '0',
    'H_RATE_YEAR': '0',
    'H_RATE_AVG': '0',
    'NOW_CO2': '153.064',
    'YEAR_CO2': '136.528',
    'AVG_CO2': '141.828',
    'TOTAL_CO2_YEAR': '16.536',
    'TOTAL_CO2_AVG': '11.236',
    'TOTAL_RATE_YEAR': '12.112',
    'TOTAL_RATE_AVG': '7.922',
    'REG_DATE': '2015-06-04 17:03:55.0'},
   {'YEAR': '2015',
    'MON': '01',
    'HOSTCODE': '중구',
    'DONGCODE': '황학동',
    'MM_TYPE': '소상공인',
    'TYPE_DIV': '단체',
    'TYPE_DIV_CD': 'TB_GROUP',
    'CNT': '1',
    'EUS': '1405',
    'EUS1': '1400',
    'EUS2': '1538',
    'ECO2_1_MATH_YEAR': '5',
    'ECO2_2_MATH_YEAR': '2.12',
    'ECO2_1_MATH': '-64',
    'ECO2_2_MATH': '-27.136',
    'ECO2_1': '-64',
    'ECO2_2': '-27.136',
    'E_TOE_YEAR': '0.00115',
    'E_RATE_YEAR': '0.357',
    'E_TOE_AVG': '-0.015',
    'E_RATE_AVG': '-4.357',
    'GUS': '0',
    'GUS1': '0',
    'GUS2': '0',
    'GCO2_1_MATH_YEAR': '0',
    'GCO2_2_MATH_YEAR': '0',
    'GCO2_1_MATH': '0',
    'GCO2_2_MATH': '0',
    'GCO2_1': '0',
    'GCO2_2': '0',
    'G_TOE_YEAR': '0',
    'G_RATE_YEAR': '0',
    'G_TOE_AVG': '0',
    'G_RATE_AVG': '0',
    'WUS': '0',
    'WUS1': '0',
    'WUS2': '0',
    'WCO2_1_MATH_YEAR': '0',
    'WCO2_2_MATH_YEAR': '0',
    'WCO2_1_MATH': '0',
    'WCO2_2_MATH': '0',
    'WCO2_1': '0',
    'WCO2_2': '0',
    'W_RATE_YEAR': '0',
    'W_RATE_AVG': '0',
    'HUS': '0',
    'HUS1': '0',
    'HUS2': '0',
    'HCO2_1': '0',
    'HCO2_2': '0',
    'H_RATE_YEAR': '0',
    'H_RATE_AVG': '0',
    'NOW_CO2': '595.72',
    'YEAR_CO2': '593.6',
    'AVG_CO2': '622.856',
    'TOTAL_CO2_YEAR': '2.12',
    'TOTAL_CO2_AVG': '-27.136',
    'TOTAL_RATE_YEAR': '0.357',
    'TOTAL_RATE_AVG': '-4.357',
    'REG_DATE': '2015-06-04 17:03:55.0'},
   {'YEAR': '2015',
    'MON': '01',
    'HOSTCODE': '중랑구',
    'DONGCODE': '면목3.8동',
    'MM_TYPE': '개인',
    'TYPE_DIV': '아파트',
    'TYPE_DIV_CD': 'TB_APT_C',
    'CNT': '1',
    'EUS': '215',
    'EUS1': '250',
    'EUS2': '250',
    'ECO2_1_MATH_YEAR': '-35',
    'ECO2_2_MATH_YEAR': '-14.84',
    'ECO2_1_MATH': '-35',
    'ECO2_2_MATH': '-14.84',
    'ECO2_1': '-35',
    'ECO2_2': '-14.84',
    'E_TOE_YEAR': '-0.00805',
    'E_RATE_YEAR': '-14',
    'E_TOE_AVG': '-0.008',
    'E_RATE_AVG': '-14',
    'GUS': '0',
    'GUS1': '0',
    'GUS2': '0',
    'GCO2_1_MATH_YEAR': '0',
    'GCO2_2_MATH_YEAR': '0',
    'GCO2_1_MATH': '0',
    'GCO2_2_MATH': '0',
    'GCO2_1': '0',
    'GCO2_2': '0',
    'G_TOE_YEAR': '0',
    'G_RATE_YEAR': '0',
    'G_TOE_AVG': '0',
    'G_RATE_AVG': '0',
    'WUS': '0',
    'WUS1': '0',
    'WUS2': '0',
    'WCO2_1_MATH_YEAR': '0',
    'WCO2_2_MATH_YEAR': '0',
    'WCO2_1_MATH': '0',
    'WCO2_2_MATH': '0',
    'WCO2_1': '0',
    'WCO2_2': '0',
    'W_RATE_YEAR': '0',
    'W_RATE_AVG': '0',
    'HUS': '0',
    'HUS1': '0',
    'HUS2': '0',
    'HCO2_1': '0',
    'HCO2_2': '0',
    'H_RATE_YEAR': '0',
    'H_RATE_AVG': '0',
    'NOW_CO2': '91.16',
    'YEAR_CO2': '106',
    'AVG_CO2': '106',
    'TOTAL_CO2_YEAR': '-14.84',
    'TOTAL_CO2_AVG': '-14.84',
    'TOTAL_RATE_YEAR': '-14',
    'TOTAL_RATE_AVG': '-14',
    'REG_DATE': '2015-06-04 17:03:55.0'},
   {'YEAR': '2015',
    'MON': '01',
    'HOSTCODE': '강동구',
    'DONGCODE': '강일동',
    'MM_TYPE': '공동주택관리소',
    'TYPE_DIV': '단체',
    'TYPE_DIV_CD': 'TB_GROUP',
    'CNT': '10',
    'EUS': '1176691',
    'EUS1': '1189993',
    'EUS2': '1283702',
    'ECO2_1_MATH_YEAR': '-13302',
    'ECO2_2_MATH_YEAR': '-5640.048',
    'ECO2_1_MATH': '-60156.5',
    'ECO2_2_MATH': '-25506.356',
    'ECO2_1': '-60156.5',
    'ECO2_2': '-25506.356',
    'E_TOE_YEAR': '-3.05946',
    'E_RATE_YEAR': '-1.118',
    'E_TOE_AVG': '-13.836',
    'E_RATE_AVG': '-4.864',
    'GUS': '36',
    'GUS1': '34',
    'GUS2': '35',
    'GCO2_1_MATH_YEAR': '2',
    'GCO2_2_MATH_YEAR': '4.48',
    'GCO2_1_MATH': '1.5',
    'GCO2_2_MATH': '3.36',
    'GCO2_1': '1.5',
    'GCO2_2': '3.36',
    'G_TOE_YEAR': '0.002',
    'G_RATE_YEAR': '5.882',
    'G_TOE_AVG': '0.002',
    'G_RATE_AVG': '4.348',
    'WUS': '36421',
    'WUS1': '34701',
    'WUS2': '35251',
    'WCO2_1_MATH_YEAR': '1720',
    'WCO2_2_MATH_YEAR': '571.04',
    'WCO2_1_MATH': '1445',
    'WCO2_2_MATH': '479.74',
    'WCO2_1': '1445',
    'WCO2_2': '479.74',
    'W_RATE_YEAR': '4.957',
    'W_RATE_AVG': '4.131',
    'HUS': '0',
    'HUS1': '0',
    'HUS2': '0',
    'HCO2_1': '0',
    'HCO2_2': '0',
    'H_RATE_YEAR': '0',
    'H_RATE_AVG': '0',
    'NOW_CO2': '511089.396',
    'YEAR_CO2': '516153.924',
    'AVG_CO2': '536112.652',
    'TOTAL_CO2_YEAR': '-5064.528',
    'TOTAL_CO2_AVG': '-25023.256',
    'TOTAL_RATE_YEAR': '-0.981',
    'TOTAL_RATE_AVG': '-4.668',
    'REG_DATE': '2015-06-04 17:03:55.0'},
   {'YEAR': '2015',
    'MON': '01',
    'HOSTCODE': '강동구',
    'DONGCODE': '강일동',
    'MM_TYPE': '기업',
    'TYPE_DIV': '단체',
    'TYPE_DIV_CD': 'TB_GROUP',
    'CNT': '6',
    'EUS': '3192',
    'EUS1': '2187',
    'EUS2': '2187',
    'ECO2_1_MATH_YEAR': '1005',
    'ECO2_2_MATH_YEAR': '426.12',
    'ECO2_1_MATH': '1005',
    'ECO2_2_MATH': '426.12',
    'ECO2_1': '1005',
    'ECO2_2': '426.12',
    'E_TOE_YEAR': '0.23115',
    'E_RATE_YEAR': '45.953',
    'E_TOE_AVG': '0.231',
    'E_RATE_AVG': '45.953',
    'GUS': '84',
    'GUS1': '76',
    'GUS2': '67',
    'GCO2_1_MATH_YEAR': '8',
    'GCO2_2_MATH_YEAR': '17.92',
    'GCO2_1_MATH': '12.5',
    'GCO2_2_MATH': '28',
    'GCO2_1': '12.5',
    'GCO2_2': '28',
    'G_TOE_YEAR': '0.008',
    'G_RATE_YEAR': '10.526',
    'G_TOE_AVG': '0.013',
    'G_RATE_AVG': '17.483',
    'WUS': '0',
    'WUS1': '0',
    'WUS2': '0',
    'WCO2_1_MATH_YEAR': '0',
    'WCO2_2_MATH_YEAR': '0',
    'WCO2_1_MATH': '0',
    'WCO2_2_MATH': '0',
    'WCO2_1': '0',
    'WCO2_2': '0',
    'W_RATE_YEAR': '0',
    'W_RATE_AVG': '0',
    'HUS': '0',
    'HUS1': '0',
    'HUS2': '0',
    'HCO2_1': '0',
    'HCO2_2': '0',
    'H_RATE_YEAR': '0',
    'H_RATE_AVG': '0',
    'NOW_CO2': '1541.568',
    'YEAR_CO2': '1097.528',
    'AVG_CO2': '1087.448',
    'TOTAL_CO2_YEAR': '444.04',
    'TOTAL_CO2_AVG': '454.12',
    'TOTAL_RATE_YEAR': '40.458',
    'TOTAL_RATE_AVG': '41.76',
    'REG_DATE': '2015-06-04 17:03:55.0'}]}}

## 데이터 프레임 생성

In [23]:
#chatgpt

import requests
import pandas as pd

# 데이터 요청
#response = requests.get(url, params=params)
#data = response.json()

# JSON 구조에서 'row' 항목만 추출
data = response.json()
rows = data['energyUseDataStatInfo']['row']

# 원하는 컬럼만 추출
filtered_data = [
    {
        'YEAR': item['YEAR'],
        'MON': item['MON'],
        'HOSTCODE': item['HOSTCODE'],
        'EUS': item['EUS'],
        'GUS': item['GUS'],
        'WUS': item['WUS'],
        'HUS': item['HUS']
    }
    for item in rows
]

# pandas DataFrame으로 변환
df = pd.DataFrame(filtered_data)

# CSV 파일로 저장
df.to_csv('energy_use_data.csv', index=False, encoding='utf-8-sig')

print("Data saved successfully as 'energy_use_data.csv'")

Data saved successfully as 'energy_use_data.csv'

In [20]:
# 서울시
import pandas as pd

## requests로부터 response, body, item 항목 읽기
data = response.json()['YEAR']['MON']['EUS']['GUS']['WUS']['HUS']
print(type(data))
print(len(data))
print(data[0])
df =pd.DataFrame(data)
#df['pm25Grade']

KeyError: 'YEAR'

In [19]:
# 수업 공공
import pandas as pd

## requests로부터 response, body, item 항목 읽기
data = response.json()['year']['body']['items']
print(type(data))
print(len(data))
print(data[0])
df =pd.DataFrame(data)
df.head()
df['pm25Grade']

KeyError: 'response'

## 다양항 형식으로 데이터 저장

In [ ]:
## csv 형식 저장
df.to_csv('air_pollution.csv', index=False, encoding='utf-8')

## JSON 형식 데이터 저장
df.to_json('air_pollution.json', indent=4, force_ascii=False)

## EXCEL 형식 데이터 저장
df.to_excel('air_pollution.xlsx', index=False)

## HTML 형식 데이터 저장
df.to_html('air_pollution.html')

In [ ]:
## 서울시
df.to_csv('air_pollution.csv', index=False, encoding='utf-8')

## JSON 형식 데이터 저장

## EXCEL 형식 데이터 저장

## HTML 형식 데이터 저장